message:
  command:
    create:
      setup:
        first: "&ePlease right-click the &abottom-left corner &eof the frame"
        second: "&ePlease right-click the &atop-right corner &eof the frame"
        set:
          first: "&aFirst corner set"
          second: "&aSecond corner set"
        complete: "&aSetup complete! &eCreating frame '%s' with image '%s'..."
        loading: "&7Loading image & generating maps..."
        starting: "&7Starting playback..."
        started: "&aAnimation started!"
      error:
        exists: "&cFrame already exists"
        invalidImage: "&cInvalid image path specified"
        unknownType: "&cCould not identify the image type. Please make sure you are using the correct link. (Generating anyway, check console for errors)"
    delete:
      stopping: "&eStopping animation..."
      removed: "&aFrame removed."
      error:
        notFound: "&cFrame not found"

# This is a (slightly hacky) fix for images which Java interpretes as the wrong image type
# You should enable this if you get this error when creating a image: http://paste.inventivetalent.org/nokomiquri
fixImageTypes: false